#!/bin/sh
export PATH="$PATH:$HOME/.config/bspwm/scripts"

# enviar parametro actualizado
pgrep -x setup > /dev/null || setup ~/Walls/lain-11.jpg &

# recargar despues de launch.sh por dual monitor (que se ejecuta en setup)
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         6
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &
# usar variables de color actualizadas
. "${HOME}/.cache/wal/colors.sh"

bspc config focus_follows_pointer true
bspc config focused_border_color "$color5"
bspc config presel_feedback_color "$color5"

#pgrep -x battery > /dev/null || battery  &

# -n solo una vez o renombra algo que no existe
# -r borrar monitor que no existe (si usas 1)
bspc monitor -d I II III IV V VI VII VII IX X
# cambiar
#bspc monitor monitor0 -s monitor1

#pkill picom
#picom --daemon --experimental-backends --config "${HOME}/.config/picom/picom.conf" &


