#!/usr/bin/env bash


username=$(getent passwd | grep "$(whoami)" | cut -f 5 -d:)
updates=$(checkupdates 2> /dev/null | wc -l)
minutes=$(uptime | awk '{print $3}')
timeunit=$(uptime | awk '{print $4}' | cut -c '1-3')

function notify() {
    if [ "$updates" -eq 0 ];
    then
        dunstify -a System -h string:x-dunst-stack-tag:welcome "Actualizaciones" "Todos los paquetes actualizados"
    else
        dunstify -a System -h string:x-dunst-stack-tag:welcome "Actualizaciones" "Actualizaciones disponibles: $updates"
    fi
}


if [ "$minutes" -lt 2 ] && [ "$timeunit" == 'min' ]; then
	dunstify -h string:x-dunst-stack-tag:welcome "Bienvenida" "$username" -t 10000 -i ~/.config/dunst/icons/apps/arch.png
	notify
fi
